In [1]:

import torch
import torch.nn as n
import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
import torch.nn.functional as f
import torch.optim as op
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.


In [0]:
(xtrain,ytrain),(xvalid,yvalid)=mnist.load_data()

In [0]:
xtrain1=xtrain.astype(np.float32)/255
yonehot=to_categorical(ytrain,10)

In [0]:
x1,y1=xtrain[:64],ytrain[:64]
x2,y2=xtrain[64:128],ytrain[64:128]

In [0]:
x1=x1.reshape(64,-1)
x2=x2.reshape(64,-1)

In [0]:
class model(n.Module):
  def __init__(self):
    super().__init__()
    self.l1=n.Linear(784,16)
    self.l2=n.Linear(16,10)
  
  def forward(self,x):
    out=f.relu(self.l1(x))
    return self.l2(out)

In [0]:
model2=model()

In [0]:
opt=op.Adam(model2.parameters(),lr=0.001)

In [0]:
x1=torch.tensor(x1).float()
y1=torch.LongTensor(y1)
x2=torch.tensor(x2).float()
y2=torch.LongTensor(y2)

In [9]:
model2.train()

model(
  (l1): Linear(in_features=784, out_features=16, bias=True)
  (l2): Linear(in_features=16, out_features=10, bias=True)
)

In [0]:
loss=n.CrossEntropyLoss()

In [0]:
x1=torch.FloatTensor(x1)
y1=torch.LongTensor(y1)

In [0]:
pred=model2.forward(x1)

In [14]:
pred.shape

torch.Size([64, 10])

In [0]:
opt.zero_grad()
loss1=loss(pred,y1)

In [0]:
loss1.backward()

In [0]:
l=list(model2.parameters())[1]

In [18]:
l.grad

tensor([ 0.0277,  0.0311,  0.0789, -0.0146,  0.1397,  0.0064,  0.0716,  0.0281,
         0.0202,  0.0117, -0.0194,  0.0504,  0.0515,  0.0385,  0.0170,  0.0296])

In [0]:
pred=model2.forward(x1)
loss1=loss(pred,y1)

In [0]:
loss1.backward()

In [24]:
l=list(model2.parameters())[1]
l.grad

tensor([ 0.0553,  0.0621,  0.1578, -0.0293,  0.2795,  0.0129,  0.1432,  0.0563,
         0.0405,  0.0234, -0.0388,  0.1007,  0.1031,  0.0769,  0.0340,  0.0592])

In [0]:
# Doing multiple backward keeps on adding the gradients to previous gradients

In [0]:
pred=model2.forward(x1)

In [0]:
l=list(model2.parameters())[1]

In [0]:
l.

In [0]:
p2=model1.forward(x2)
l2=loss(p2,y2)

In [0]:
l2.backward()

In [0]:
l=list(model1.parameters())[1]

In [91]:
l.grad

tensor([-0.0248,  0.1098, -0.0093, -0.0205, -0.0097,  0.0323,  0.1816, -0.0049,
         0.0644,  0.0239,  0.0184, -0.0537,  0.0755,  0.0060,  0.0597,  0.0603])

In [0]:
p1=model1.forward(x1)
l1=loss(p1,y1)
l1.backward()
l=list(model1.parameters())[1]

In [93]:
l.grad

tensor([-0.0300,  0.2327,  0.0049, -0.0711, -0.0157,  0.0694,  0.3721,  0.0198,
         0.1309,  0.0337,  0.0252, -0.1052,  0.1722, -0.0078,  0.1495,  0.1156])

In [94]:
l1

tensor(33.3876, grad_fn=<NllLossBackward>)